### ISSUE TITLE
Improve navbar of the blog website

### ISSUE THREAD

**Issue by jonmichael69** [jonmichael69/hacktoberfest2022-WebDev#1]

**Comment by srijoy-paul** [comment]
@jonmichael69  Please assign me this task

**Comment by srijoy-paul** [comment]
Working on this

**Comment by srijoy-paul** [comment]
I have raised a PR #10 , Please review it

**Comment by sudhanshusharma99** [comment]
@jonmichael69  Please assign me this task

**Comment by srijoy-paul** [comment]
@jonmichael69 What, i have worked on this and raised a pr 
if you are not accepting participation from other why did you make it public
Please reply this

**Comment by jonmichael69** [comment]
> @jonmichael69 What, i have worked on this and raised a pr if you are not accepting participation from other why did you make it public Please reply this

Hello @srijoy-paul 
We are really sorry, we are getting too many requests in multiple repos and we mistakenly assign this issue to someone else but don't worry from now you can create new issue and solve the issue We will add the hacktoberfest labels.
Thank you for the understanding.
Happy Coding

Team KodeShala
