### ISSUE TITLE
Want to work on About page of the Website. 

### ISSUE THREAD

**Issue by hardik-pratap-singh** [jonmichael69/hacktoberfest2022-WebDev#18]
As there is a link for the about page but actually there is not about page in this site. I want to add a About page which will be in sync with the rest of the project 

I want to work on this issue !
May I ?

**Comment by hardik-pratap-singh** [comment]
Hello @jonmichael69 ! 

I was working on my About page from last 1 hour and when I was about to make the PR, it showed "can't automatically merge". How to come out of this situation ? 
Can you help me ? 

Thanks !

**Comment by jonmichael69** [comment]
> Hello @jonmichael69 !
> 
> I was working on my About page from last 1 hour and when I was about to make the PR, it showed "can't automatically merge". How to come out of this situation ? Can you help me ?
> 
> Thanks !

Hello @hardik-pratap-singh 
First of all you have to fork this repo and then git clone into your local device afterthat start contributing using any text editor and then push thế updated code.
And after successfully pushing the code make sure to create pull request and then I’ll check the request and successfully merged your changes.

**Comment by imNilabja** [comment]
I want to work on this task could you assign me.

**Comment by imNilabja** [comment]
I would like to work on this task can you assign me please

**Comment by imNilabja** [comment]
@jonmichael69  I would like to work on this task can you assign me please
