### ISSUE TITLE
Fix Login.html

### ISSUE THREAD

**Issue by jonmichael69** [jonmichael69/hacktoberfest2022-WebDev#24]
1. Rename Login.html to login.html
2. add login to navbar in all html files
3. improve design of login.html
4. create signup.html

**Comment by Santhusha-bit** [comment]
I'll fix it

**Comment by jsvigneshkanna** [comment]
Please assign this to my name, will work on it

**Comment by jineshnagori** [comment]
I'll fix these all issues regarding login page please assign this issue to me
