### ISSUE TITLE
Responsive issue in blogpost.html

### ISSUE THREAD

**Issue by jonmichael69** [jonmichael69/hacktoberfest2022-WebDev#27]

**Comment by syprogrammer** [comment]
i have required knowledge please assign it to me

**Comment by syprogrammer** [comment]
@jonmichael69 here is the changes i made is it ok now: https://bit.ly/3eh3Jtj

**Comment by jonmichael69** [comment]
> @jonmichael69 here is the changes i made is it ok now: https://bit.ly/3eh3Jtj

Hello @syprogrammer 
Your design looks good now you can contribute.

Thank you
Happy codinh
