### ISSUE TITLE
Change hero section in index.html file

### ISSUE THREAD

**Issue by jonmichael69** [jonmichael69/hacktoberfest2022-WebDev#30]

**Comment by amitroy-thedev** [comment]
Hey @jonmichael69 can you elaborate more on this ..

**Comment by SrishtiDharwani** [comment]
hey @jonmichael69 how do you want it changed?

**Comment by amitroy-thedev** [comment]
hey @jonmichael69 i can give it a try you can assign me for this project

**Comment by jonmichael69** [comment]
> Hey @jonmichael69 can you elaborate more on this ..

Please check the inde.html page where i commented the hero section so your task is to create something different.
