### ISSUE TITLE
Navbar not working in mobile

### ISSUE THREAD

**Issue by jonmichael69** [jonmichael69/hacktoberfest2022-WebDev#39]
Only index.html mobile navbar working
Please correct code from each and every file containing navbar.

thank you

**Comment by najeebkp** [comment]
Hi @jonmichael69 please assign me this task

**Comment by ankitkumar0622** [comment]
hi can you please assign me this task , i would  love to work on it .!!

**Comment by flying-solo** [comment]
@jonmichael69  i would like to work on this issue , if @ankitkumar0622  is not working on it assign it to me.

**Comment by najeebkp** [comment]
@jonmichael69  please assign any one. how can multiple people work on same issue?

**Comment by ankitkumar0622** [comment]
@jonmichael69 ive made the changes and the navbar is working perfectly on mobile , my pull request is #46
