### ISSUE TITLE
Add scroll bar in About tab

### ISSUE THREAD

**Issue by PumpkinManiac** [jonmichael69/hacktoberfest2022-WebDev#52]
add scroll bar in about tab 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/115183346/194867717-d7cd2cb6-9bd1-481d-a3e2-412fcac8e264.png">

**Comment by Devesh-coder** [comment]
Hey, @jonmichael69 I would like to solve this issue!

**Comment by aks057** [comment]
can you assign this issue?

**Comment by Devesh-coder** [comment]
#59 Added scroll bar in About tab,
