### ISSUE TITLE
Improve Styling (CSS) of Contact and Register tab

### ISSUE THREAD

**Issue by PumpkinManiac** [jonmichael69/hacktoberfest2022-WebDev#53]

**Comment by PumpkinManiac** [comment]
@jonmichael69 I am currently working on it

**Comment by jonmichael69** [comment]
> @jonmichael69 I am currently working on it

Ok @PumpkinManiac

**Comment by jonmichael69** [comment]
> @jonmichael69 I am currently working on it

Hey @PumpkinManiac 
What’s the progress?

**Comment by PumpkinManiac** [comment]
@jonmichael69 Will done by today

**Comment by imNilabja** [comment]
I would like to do this task can you assign me

**Comment by flying-solo** [comment]
@jonmichael69  i would love to work on this issue kindly assign it to me.

**Comment by flying-solo** [comment]
@jonmichael69  should i improve the design by my own or is there any input from your side

**Comment by jonmichael69** [comment]
> @jonmichael69 should i improve the design by my own or is there any input from your side

You change by your own.

**Comment by prekshamohre** [comment]
I ll improve About us page
