### ISSUE TITLE
Improve footer style

### ISSUE THREAD

**Issue by MuskanGarg24** [jonmichael69/hacktoberfest2022-WebDev#74]

**Comment by MuskanGarg24** [comment]
@jonmichael69  Hey! Can you please assign me this?

**Comment by Aliksarkar18** [comment]
Can I contribute this project ,Please Assign me @jonmichael69

**Comment by abhijit812** [comment]
@jonmichael69 Can you assign me this project?

**Comment by abhijit49** [comment]
@jonmichael69 you can unassign me and  give @anujpatel581 and @imNilabja the chance to work on this issue
